module.exports = {
  caseType:'clinician_visible_care_support_observation', initialState:'consent_pending',
  states:['consent_pending','observation_validated','uncertainty_review','clinician_review','followup_owned','care_support_active','escalated','resolved','closed'],
  createRoles:['care_coordinator','clinician'],
  assessmentRoles:['care_coordinator','clinician','safety_reviewer'],
  auditRoles:['clinical_supervisor','safety_reviewer','privacy_officer'],
  connectorRoles:['clinical_supervisor','integration_operator'],
  evidenceKinds:['consent_receipt','observation_digest','source_version_manifest','missing_data_report','contraindication_screen','calibration_report','bias_evaluation','clinician_review','followup_assignment','escalation_receipt','safety_plan_version','resolution_record'],
  requiredSignals:['consentVerified','observationVersion','missingDataStatus','contraindicationStatus','escalationStatus','clinicianAvailable','policyVersion'],
  professionalBoundary:'This is non-diagnostic support; it cannot diagnose, prescribe, alter medication, provide emergency care, or replace a licensed clinician.',
  connectors:[
    {name:'ehr_fhir',purpose:'consented observation and care-plan references'},
    {name:'pharmacy',purpose:'read-only medication-list versions'},
    {name:'scheduling',purpose:'clinician follow-up receipts'},
    {name:'device_feed',purpose:'consented digest-only observations'},
    {name:'clinician_messaging',purpose:'secure escalation and acknowledgement receipts'},
    {name:'payer',purpose:'administrative coverage references only'},
  ],
  transitions:[
    {from:'consent_pending',action:'validate_observation',to:'observation_validated',roles:['care_coordinator','clinician'],requiresEvidence:true},
    {from:'observation_validated',action:'review_uncertainty',to:'uncertainty_review',roles:['safety_reviewer','clinician'],requiresEvidence:true},
    {from:'uncertainty_review',action:'submit_clinician_review',to:'clinician_review',roles:['clinician'],requiresEvidence:true,dualControl:true},
    {from:'clinician_review',action:'assign_followup',to:'followup_owned',roles:['care_coordinator','clinician'],requiresEvidence:true},
    {from:'followup_owned',action:'activate_support',to:'care_support_active',roles:['clinician'],requiresEvidence:true,dualControl:true},
    {from:'care_support_active',action:'escalate',to:'escalated',roles:['clinician','safety_reviewer'],requiresEvidence:true},
    {from:'escalated',action:'resolve',to:'resolved',roles:['clinician','clinical_supervisor'],requiresEvidence:true,dualControl:true},
    {from:'resolved',action:'close',to:'closed',roles:['clinical_supervisor'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const urgent=x.escalationStatus==='urgent';const unsafe=x.consentVerified!==true||x.missingDataStatus!=='complete'||x.contraindicationStatus!=='cleared'||x.clinicianAvailable!==true;return{disposition:urgent?'immediate_human_escalation_required':unsafe?'clinical_data_or_consent_hold':'clinician_review_required',diagnosis:null,medicationRecommendation:null,automatedEscalation:false,observationVersion:x.observationVersion};},
};
