const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {createWorkflow}=require('./workflowCore.cjs');const {validateRuntime}=require('./runtime.cjs');const config=require('./config.cjs');const workflow=createWorkflow(config);const headers={'x-tenant-id':'clinic-a','idempotency-key':'request-a'};
const accepted={consentVerified:true,observationVersion:'obs-v3',missingDataStatus:'complete',contraindicationStatus:'cleared',escalationStatus:'routine',clinicianAvailable:true,policyVersion:'policy-v1'};
test('clinician-visible care topology and connectors are declared',()=>{assert.ok(config.states.includes(config.initialState));assert.ok(config.transitions.length>2);assert.ok(config.connectors.length>2);for(const r of config.transitions){assert.ok(config.states.includes(r.from));assert.ok(config.states.includes(r.to));assert.ok(r.roles.length);}});
test('tenant, idempotency, actor and clinical roles fail closed',()=>{assert.throws(()=>workflow.context({}, {id:'a',role:'clinician'}),/X-Tenant-Id/);const c=workflow.context(headers,{id:'clinician-a',role:'clinician'});assert.equal(workflow.createCase({subjectRef:'care-case-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z',retentionUntil:'2027-07-18T00:00:00Z'},c).state,config.initialState);assert.throws(()=>workflow.createCase({subjectRef:'care-case-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z'},{...c,role:'visitor'}),/Role cannot create/);});
test('clinical evidence is opaque and digest verified',()=>{assert.equal(workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'ehr:consent-17',sourceVersion:'v1',sha256:'a'.repeat(64),capturedAt:'2026-07-18T10:00:00Z',consentBasis:'explicit-consent-v1'}).sha256,'a'.repeat(64));assert.throws(()=>workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'ehr:x',sourceVersion:'v1',sha256:'bad',capturedAt:'2026-07-18T10:00:00Z'}),/sha256/);});
test('routine complete observations require clinician review and urgent signals escalate',()=>{const c=workflow.context(headers,{id:'clinician-a',role:'clinician'});assert.equal(workflow.deterministicAssessment({},c).disposition,'insufficient_evidence');const good=workflow.deterministicAssessment(accepted,c);assert.equal(good.disposition,'clinician_review_required');assert.equal(good.diagnosis,null);assert.equal(good.medicationRecommendation,null);assert.equal(good.automatedEscalation,false);assert.equal(workflow.deterministicAssessment({...accepted,escalationStatus:'urgent'},c).disposition,'immediate_human_escalation_required');assert.equal(workflow.deterministicAssessment({...accepted,consentVerified:false},c).disposition,'clinical_data_or_consent_hold');});
test('transitions require consent evidence, versions and clinician dual control',()=>{const r=config.transitions[0];const c=workflow.context(headers,{id:'actor-b',role:r.roles[0]});const rec={state:r.from,version:1,evidenceCount:0,createdBy:'actor-a',lastActorId:null};assert.throws(()=>workflow.transition(rec,{action:r.action,expectedVersion:1,reason:'validated consented observation'},c),/evidence/);assert.throws(()=>workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:2,reason:'validated consented observation'},c),/changed/);assert.equal(workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:1,reason:'validated consented observation'},c).to,r.to);const d=config.transitions.find(x=>x.dualControl);const dc=workflow.context(headers,{id:'actor-b',role:d.roles[0]});assert.throws(()=>workflow.transition({state:d.from,version:2,evidenceCount:1,createdBy:'actor-a',lastActorId:'actor-b'},{action:d.action,expectedVersion:2,reason:'independent clinician review'},dc),/second person/);});
test('runtime safety rejects weak or demo production config',()=>{assert.throws(()=>validateRuntime({NODE_ENV:'test',JWT_SECRET:'short'}),/JWT_SECRET/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'*'}),/allowlist/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'https://client.example',ALLOW_MOCK_PROVIDERS:'true'}),/prohibited/);assert.equal(validateRuntime({NODE_ENV:'test',JWT_SECRET:'x'.repeat(40)}),true);});
test('migration and launcher are append-only and nondestructive',()=>{const root=path.resolve(__dirname,'..','..');const m=fs.readFileSync(path.join(root,'server/migrations/001_governed_care_support.sql'),'utf8');const s=fs.readFileSync(path.join(root,'start.sh'),'utf8');assert.match(m,/governed_tenant_memberships/);assert.match(m,/governed_connector_failures/);assert.match(m,/append-only/);assert.doesNotMatch(s,/kill\s+-9|pkill|dropdb|createdb|npm\s+install|seed\.js|psql\s+.*-f/);});
