-- Seed Data for Mental Health Companion

-- Users (password123 and admin123 respectively)
INSERT INTO users (email, password_hash, name) VALUES
('demo@mentalhealth.com', '$2a$10$ytFa65ECuvdqFT/9s0hsgOZR3i4G3rO4QHKmcmkrpOoTchAu8rti6', 'Demo User'),
('admin@mentalhealth.com', '$2a$10$rKoX8/uURvooGldxlP0qPe6vyvjB5aPzFh63IPZ6MJQM0BR7PB7/S', 'Admin User')
ON CONFLICT (email) DO NOTHING;

-- Moods (for user_id=1)
INSERT INTO moods (user_id, mood_level, mood_label, notes, factors) VALUES
(1, 8, 'Happy', 'Had a great morning workout and productive day at work.', ARRAY['exercise', 'productivity']),
(1, 6, 'Content', 'Quiet evening reading a book. Feeling at peace.', ARRAY['relaxation', 'reading']),
(1, 3, 'Anxious', 'Big presentation tomorrow. Cant stop thinking about it.', ARRAY['work stress', 'anticipation']),
(1, 7, 'Grateful', 'Spent quality time with family today.', ARRAY['family', 'connection']),
(1, 4, 'Sad', 'Missing an old friend who moved away.', ARRAY['loneliness', 'nostalgia']),
(1, 9, 'Excited', 'Got accepted into the volunteer program I applied for!', ARRAY['achievement', 'purpose']),
(1, 5, 'Neutral', 'Ordinary day. Nothing particularly good or bad happened.', ARRAY['routine']),
(1, 2, 'Overwhelmed', 'Too many deadlines piling up at once.', ARRAY['work stress', 'time pressure']),
(1, 7, 'Calm', 'Meditation session really helped today.', ARRAY['meditation', 'mindfulness']),
(1, 6, 'Hopeful', 'Started therapy and feeling optimistic about the process.', ARRAY['therapy', 'self-improvement']),
(1, 8, 'Energetic', 'Great sleep last night and morning yoga.', ARRAY['sleep', 'exercise']),
(1, 3, 'Frustrated', 'Argument with a coworker about project direction.', ARRAY['conflict', 'work']),
(1, 5, 'Reflective', 'Journaling helped me process some difficult emotions.', ARRAY['journaling', 'self-reflection']),
(1, 9, 'Joyful', 'Surprise birthday party from friends!', ARRAY['friendship', 'celebration']),
(1, 4, 'Tired', 'Insomnia kept me up most of the night.', ARRAY['sleep issues', 'fatigue']);

-- Journal Entries (for user_id=1)
INSERT INTO journal_entries (user_id, title, content, mood, tags, is_private) VALUES
(1, 'Finding My Morning Routine', 'I have been experimenting with waking up earlier and starting my day with intention. Today I tried a 20-minute meditation followed by journaling, and it completely changed the tone of my day. I felt more centered and less reactive to stressful situations at work.', 'calm', ARRAY['routine', 'meditation', 'morning'], true),
(1, 'Dealing with Work Anxiety', 'The quarterly review is coming up and I can feel the anxiety building. I noticed my shoulders tensing and my breathing getting shallow. I tried the 4-7-8 breathing technique and it helped somewhat. I need to remind myself that I have prepared well.', 'anxious', ARRAY['work', 'anxiety', 'breathing'], true),
(1, 'Gratitude for Small Things', 'Today I noticed the sunlight filtering through the trees on my walk. A stranger smiled at me. My coffee was perfect. Sometimes happiness is found in the smallest moments if we pay attention.', 'grateful', ARRAY['gratitude', 'mindfulness', 'nature'], false),
(1, 'Processing a Difficult Conversation', 'Had a tough talk with my partner about our communication patterns. It was uncomfortable but necessary. I am learning that discomfort in the short term often leads to growth in the long term. We agreed to practice active listening more.', 'reflective', ARRAY['relationships', 'communication', 'growth'], true),
(1, 'Celebrating Progress', 'Three months ago I could barely get out of bed on difficult days. Today I completed a 5K run. The journey from there to here was not linear, but looking back I can see how much I have grown. Therapy and consistent self-care made this possible.', 'proud', ARRAY['progress', 'exercise', 'therapy'], false),
(1, 'Navigating Social Anxiety', 'Went to a networking event tonight. My instinct was to leave after five minutes, but I used the grounding technique my therapist taught me. I ended up having two meaningful conversations. Small victories matter.', 'accomplished', ARRAY['social anxiety', 'coping', 'networking'], true),
(1, 'Rainy Day Reflections', 'The rain outside matches my mood today, and that is okay. Not every day needs to be sunshine. I am learning to sit with uncomfortable emotions instead of running from them. This is what they call radical acceptance.', 'melancholy', ARRAY['acceptance', 'emotions', 'rain'], true),
(1, 'Boundaries Are Hard but Necessary', 'Said no to a social obligation today because I needed rest. Felt guilty at first, but then relief washed over me. Setting boundaries is an act of self-love, not selfishness. My therapist would be proud.', 'empowered', ARRAY['boundaries', 'self-care', 'growth'], true),
(1, 'The Power of Connection', 'Called my best friend after weeks of isolation. We talked for two hours. I forgot how healing it is to be truly heard by someone who cares. I need to stop isolating when things get tough.', 'connected', ARRAY['friendship', 'connection', 'isolation'], false),
(1, 'Mindful Eating Journey', 'Started practicing mindful eating today. Instead of scrolling my phone during lunch, I actually tasted my food. It was a simple salad but I noticed flavors I had never paid attention to before. Presence transforms ordinary experiences.', 'mindful', ARRAY['mindfulness', 'eating', 'presence'], false),
(1, 'Insomnia Struggles', 'Third night in a row with disrupted sleep. My mind races the moment my head hits the pillow. I have tried warm tea, reading, and white noise. Going to discuss sleep hygiene strategies with my therapist next session.', 'exhausted', ARRAY['sleep', 'insomnia', 'health'], true),
(1, 'A Letter to My Younger Self', 'If I could tell my younger self one thing, it would be that asking for help is strength, not weakness. So many years spent suffering in silence when support was available. I am grateful I finally reached out.', 'compassionate', ARRAY['self-compassion', 'reflection', 'healing'], false),
(1, 'Nature as Medicine', 'Spent the afternoon hiking in the mountains. There is something profoundly healing about being surrounded by trees and fresh air. My worries seemed smaller against the backdrop of ancient peaks. Need to make this a weekly practice.', 'peaceful', ARRAY['nature', 'hiking', 'healing'], false),
(1, 'Anger Management Progress', 'Situation at work that would have sent me spiraling six months ago. Instead of reacting, I paused, took three deep breaths, and responded calmly. The DBT skills are actually working. Emotional regulation is a skill that improves with practice.', 'proud', ARRAY['anger', 'DBT', 'coping'], true),
(1, 'Year-End Mental Health Review', 'Looking back at this year, I can see tremendous growth. Started therapy in January, began medication in March, joined a support group in June. Each step built on the last. I am not where I want to be yet, but I am so far from where I started.', 'hopeful', ARRAY['review', 'growth', 'therapy', 'progress'], false);

-- Meditation Sessions
INSERT INTO meditation_sessions (title, description, duration_minutes, category, difficulty, audio_url, image_url, instructions) VALUES
('Morning Mindfulness', 'Start your day with clarity and intention through this gentle mindfulness meditation.', 10, 'mindfulness', 'beginner', '/audio/morning-mindfulness.mp3', '/images/meditation/morning.jpg', 'Find a comfortable seated position. Close your eyes gently. Begin by taking three deep breaths. Now let your breathing return to its natural rhythm. Simply observe each breath as it flows in and out. When your mind wanders, gently guide it back to the breath. Set your intention for the day ahead.'),
('Body Scan Relaxation', 'A thorough body scan to release tension and promote deep relaxation.', 20, 'body scan', 'beginner', '/audio/body-scan.mp3', '/images/meditation/body-scan.jpg', 'Lie down comfortably. Close your eyes. Starting at the top of your head, slowly bring awareness to each part of your body. Notice any sensations without judgment. Breathe into areas of tension. Gradually move down through your face, neck, shoulders, arms, torso, hips, legs, and feet. Feel your entire body relaxed and connected.'),
('Loving-Kindness Meditation', 'Cultivate compassion for yourself and others through this heart-opening practice.', 15, 'loving-kindness', 'intermediate', '/audio/loving-kindness.mp3', '/images/meditation/loving-kindness.jpg', 'Sit comfortably and close your eyes. Place your hand on your heart. Begin by directing loving-kindness toward yourself: May I be happy. May I be healthy. May I be safe. May I live with ease. Extend these wishes to a loved one, then a neutral person, then someone difficult, and finally all beings everywhere.'),
('Stress Relief Meditation', 'Release accumulated stress and find your center of calm.', 12, 'stress relief', 'beginner', '/audio/stress-relief.mp3', '/images/meditation/stress-relief.jpg', 'Sit or lie down comfortably. Take five deep cleansing breaths. Visualize stress as a color leaving your body with each exhale. Imagine breathing in calm, peaceful energy. Scan your body for tension and consciously release it. Repeat the mantra: I release what no longer serves me.'),
('Sleep Meditation', 'Drift into peaceful sleep with this calming bedtime meditation.', 25, 'sleep', 'beginner', '/audio/sleep-meditation.mp3', '/images/meditation/sleep.jpg', 'Lie in bed comfortably. Close your eyes. Begin with slow, deep breaths. Count backwards from 100, pausing between each number. Visualize yourself in a peaceful place - perhaps a quiet beach or serene forest. Let the sounds and sensations of this place carry you toward sleep. Release the day with gratitude.'),
('Anxiety Relief Meditation', 'Ground yourself and reduce anxiety with this focused breathing practice.', 10, 'anxiety relief', 'beginner', '/audio/anxiety-relief.mp3', '/images/meditation/anxiety.jpg', 'Find a comfortable position. Place both feet firmly on the ground. Take three grounding breaths. Name five things you can see, four you can hear, three you can touch, two you can smell, one you can taste. This is the 5-4-3-2-1 grounding technique. Return to your breath and feel the anxiety dissolving.'),
('Focused Attention Meditation', 'Strengthen your concentration and mental clarity through focused attention.', 15, 'focus', 'intermediate', '/audio/focused-attention.mp3', '/images/meditation/focus.jpg', 'Sit upright with good posture. Choose a single point of focus - your breath, a candle flame, or a sound. Direct all your attention to this anchor. When your mind wanders, note the distraction without judgment and return to your focus point. With practice, your periods of sustained attention will lengthen.'),
('Walking Meditation', 'Bring mindfulness into movement with this gentle walking practice.', 15, 'mindfulness', 'beginner', '/audio/walking-meditation.mp3', '/images/meditation/walking.jpg', 'Find a quiet path, indoors or outdoors. Stand still for a moment, feeling your feet on the ground. Begin walking slowly. Notice the sensation of lifting your foot, moving it forward, placing it down. Coordinate your breathing with your steps. Be fully present with each step. Let walking become a moving meditation.'),
('Chakra Balancing Meditation', 'Align and balance your energy centers for holistic wellbeing.', 30, 'energy', 'advanced', '/audio/chakra-balancing.mp3', '/images/meditation/chakra.jpg', 'Sit comfortably with spine erect. Begin at the root chakra at the base of your spine. Visualize a red spinning wheel of energy. Breathe into this center. Move upward through each chakra: sacral (orange), solar plexus (yellow), heart (green), throat (blue), third eye (indigo), crown (violet). Spend 3-4 minutes on each center.'),
('Gratitude Meditation', 'Cultivate a deep sense of thankfulness and appreciation for life.', 10, 'gratitude', 'beginner', '/audio/gratitude-meditation.mp3', '/images/meditation/gratitude.jpg', 'Sit comfortably and close your eyes. Take three centering breaths. Begin to think of things you are grateful for. Start small - the air you breathe, the ground beneath you. Expand to people, experiences, and opportunities. Feel gratitude as a warm glow in your chest. Carry this feeling with you throughout your day.'),
('Progressive Muscle Relaxation', 'Systematically tense and release muscle groups for deep physical relaxation.', 20, 'relaxation', 'beginner', '/audio/pmr.mp3', '/images/meditation/pmr.jpg', 'Lie down comfortably. Starting with your feet, tense the muscles tightly for 5 seconds, then release completely. Notice the difference between tension and relaxation. Move upward through calves, thighs, glutes, abdomen, chest, hands, arms, shoulders, neck, and face. End with a full-body relaxation.'),
('Visualization for Healing', 'Use the power of visualization to promote emotional and physical healing.', 15, 'visualization', 'intermediate', '/audio/healing-visualization.mp3', '/images/meditation/healing.jpg', 'Close your eyes and breathe deeply. Imagine a warm, golden light above your head. This light represents healing energy. Visualize it slowly flowing down through your body, touching every cell with its warmth. Where there is pain or tension, see the light dissolving it. Feel yourself becoming lighter, freer, and more whole.'),
('Mindful Breathing Meditation', 'A simple yet profound practice centered entirely on the breath.', 10, 'breathwork', 'beginner', '/audio/mindful-breathing.mp3', '/images/meditation/breathing.jpg', 'Sit in a comfortable position. Close your eyes. Without changing your breathing pattern, simply observe your breath. Notice the cool air entering your nostrils. Feel your chest and belly expand. Notice the warm air leaving. Count each exhale up to ten, then start over. If you lose count, simply begin again without judgment.'),
('Self-Compassion Meditation', 'Develop kindness and understanding toward yourself through this nurturing practice.', 15, 'self-compassion', 'intermediate', '/audio/self-compassion.mp3', '/images/meditation/self-compassion.jpg', 'Sit comfortably and place your hand on your heart. Think of a difficulty you are facing. Acknowledge the pain: This is a moment of suffering. Remind yourself: Suffering is part of being human. Offer yourself kindness: May I give myself the compassion I need. Breathe deeply and feel warmth radiating from your heart center.'),
('Ocean Waves Meditation', 'Let the rhythm of ocean waves carry you to a state of deep peace.', 20, 'nature', 'beginner', '/audio/ocean-waves.mp3', '/images/meditation/ocean.jpg', 'Lie down and close your eyes. Imagine yourself on a warm, quiet beach. Hear the gentle rhythm of waves. Let your breathing match the ocean - inhale as the wave comes in, exhale as it recedes. Feel the warm sand beneath you. Let each wave wash away worry and tension. Sink deeper into relaxation with each breath.');

-- Breathing Exercises
INSERT INTO breathing_exercises (title, description, inhale_seconds, hold_seconds, exhale_seconds, rounds, category, benefits) VALUES
('Box Breathing', 'A technique used by Navy SEALs to stay calm and focused under pressure. Equal parts inhale, hold, exhale, and hold.', 4, 4, 4, 4, 'calming', 'Reduces stress, improves focus, regulates the autonomic nervous system, and promotes mental clarity.'),
('4-7-8 Breathing', 'Developed by Dr. Andrew Weil, this technique acts as a natural tranquilizer for the nervous system.', 4, 7, 8, 4, 'sleep', 'Promotes sleep, reduces anxiety, helps manage cravings, and controls anger responses.'),
('Diaphragmatic Breathing', 'Deep belly breathing that engages the diaphragm for maximum oxygen exchange and relaxation.', 4, 0, 6, 6, 'relaxation', 'Lowers blood pressure, reduces heart rate, strengthens the diaphragm, and improves core stability.'),
('Alternate Nostril Breathing', 'An ancient yogic technique (Nadi Shodhana) that balances the left and right hemispheres of the brain.', 4, 4, 4, 8, 'balance', 'Harmonizes brain hemispheres, reduces anxiety, enhances cardiovascular function, and improves focus.'),
('Pursed Lip Breathing', 'A technique that slows breathing down and keeps airways open longer, improving oxygen exchange.', 2, 0, 4, 8, 'respiratory', 'Improves ventilation, releases trapped air, reduces shortness of breath, and promotes relaxation.'),
('Energizing Breath (Bellows)', 'A rapid breathing technique from yoga (Bhastrika) that increases energy and alertness.', 1, 0, 1, 20, 'energizing', 'Increases energy, improves alertness, boosts oxygen supply, and stimulates the sympathetic nervous system.'),
('Resonant Breathing', 'Breathing at a rate of 5 breaths per minute to achieve heart rate variability coherence.', 6, 0, 6, 5, 'coherence', 'Maximizes heart rate variability, reduces stress, balances the nervous system, and promotes emotional regulation.'),
('Lions Breath', 'A playful yoga breathing technique that releases tension in the face and throat.', 4, 0, 4, 5, 'tension release', 'Relieves tension in face and jaw, reduces stress, improves circulation to the face, and boosts confidence.'),
('Humming Bee Breath', 'A calming technique (Bhramari) that uses humming vibrations to soothe the mind.', 4, 0, 8, 6, 'calming', 'Calms the mind quickly, reduces agitation, lowers blood pressure, and promotes healing through vibration.'),
('Ocean Breath (Ujjayi)', 'A gentle restriction of the throat creates an ocean-like sound during breathing.', 4, 0, 6, 8, 'meditation', 'Builds internal heat, improves concentration, regulates body temperature, and deepens meditation practice.'),
('Wim Hof Technique', 'A powerful breathing method developed by Wim Hof combining hyperventilation with breath retention.', 2, 15, 2, 3, 'advanced', 'Boosts immune system, increases energy, reduces inflammation, and improves cold tolerance.'),
('Morning Wake-Up Breath', 'A gentle breathing pattern to energize your morning without overwhelming your system.', 3, 2, 3, 6, 'energizing', 'Gentle awakening, increases morning alertness, oxygenates the body, and sets a positive tone for the day.'),
('5-5-5 Triangle Breathing', 'A balanced triangular breathing pattern for steady calm throughout the day.', 5, 5, 5, 5, 'calming', 'Creates steady calm, easy to remember, suitable for all skill levels, and effective for mild anxiety.'),
('Extended Exhale Breathing', 'Longer exhales activate the parasympathetic nervous system for deep relaxation.', 3, 0, 7, 6, 'relaxation', 'Activates rest-and-digest response, deeply calming, reduces heart rate, and excellent before sleep.'),
('Counted Breathing', 'Simple counting technique to anchor attention and reduce racing thoughts.', 4, 2, 4, 8, 'focus', 'Improves concentration, reduces racing thoughts, accessible for beginners, and can be done anywhere.');

-- Self-Care Activities
INSERT INTO self_care_activities (title, description, category, duration_minutes, difficulty, benefits, image_url) VALUES
('Warm Bath with Essential Oils', 'Draw a warm bath infused with lavender or eucalyptus essential oils. Light candles and play soft music for a full sensory relaxation experience.', 'physical', 30, 'easy', 'Relieves muscle tension, promotes relaxation, improves sleep quality, and provides aromatherapy benefits.', '/images/selfcare/bath.jpg'),
('Nature Walk', 'Take a mindful walk in a park or natural setting. Leave your phone behind and engage all your senses in the natural environment.', 'physical', 45, 'easy', 'Reduces cortisol levels, improves mood, provides gentle exercise, and enhances connection to nature.', '/images/selfcare/nature-walk.jpg'),
('Creative Art Journaling', 'Combine writing and drawing in a journal. Use colors, doodles, and words to express your current emotional state without judgment.', 'creative', 30, 'easy', 'Processes emotions nonverbally, stimulates creativity, reduces stress, and provides a tangible record of growth.', '/images/selfcare/art-journal.jpg'),
('Digital Detox Hour', 'Put all devices in another room for a full hour. Read a physical book, do a puzzle, or simply sit with your thoughts.', 'mental', 60, 'moderate', 'Reduces screen fatigue, improves attention span, decreases comparison anxiety, and promotes presence.', '/images/selfcare/digital-detox.jpg'),
('Cook a Nourishing Meal', 'Prepare a healthy meal from scratch. Focus on whole ingredients and enjoy the meditative process of cooking.', 'physical', 60, 'moderate', 'Provides nutrition, offers a sense of accomplishment, is meditative, and encourages mindful eating.', '/images/selfcare/cooking.jpg'),
('Gentle Yoga Flow', 'Follow a gentle 20-minute yoga sequence focusing on stretching and breathing. Perfect for beginners and those with limited mobility.', 'physical', 20, 'easy', 'Increases flexibility, reduces tension, improves body awareness, and connects breath with movement.', '/images/selfcare/yoga.jpg'),
('Gratitude Letter Writing', 'Write a heartfelt letter of gratitude to someone who has positively impacted your life. You can choose to send it or keep it.', 'emotional', 20, 'easy', 'Strengthens relationships, boosts positive emotions, cultivates gratitude, and processes meaningful memories.', '/images/selfcare/letter.jpg'),
('Progressive Muscle Relaxation', 'Systematically tense and release each muscle group in your body while lying comfortably. Great for bedtime.', 'physical', 15, 'easy', 'Releases physical tension, improves body awareness, promotes sleep, and reduces anxiety symptoms.', '/images/selfcare/relaxation.jpg'),
('Playlist Curation', 'Create themed playlists for different moods - one for energy, one for calm, one for processing emotions. Music is powerful medicine.', 'creative', 20, 'easy', 'Emotional regulation through music, creative expression, builds a personal wellness toolkit, and is enjoyable.', '/images/selfcare/music.jpg'),
('Boundary Setting Practice', 'Identify one area where you need stronger boundaries. Write down what the boundary is, why it matters, and how you will communicate it.', 'emotional', 15, 'challenging', 'Protects emotional energy, improves relationships, builds self-respect, and reduces resentment.', '/images/selfcare/boundaries.jpg'),
('Mindful Tea Ceremony', 'Prepare tea with full attention to the process. Notice the aroma, warmth, and taste. Make it a personal ritual of peace.', 'mindfulness', 15, 'easy', 'Cultivates presence, creates a calming ritual, hydrates the body, and provides a daily anchor point.', '/images/selfcare/tea.jpg'),
('Declutter One Space', 'Choose one drawer, shelf, or corner to organize. Physical order often translates to mental clarity.', 'environmental', 30, 'moderate', 'Reduces visual clutter stress, provides sense of control, immediate visible results, and meditative process.', '/images/selfcare/declutter.jpg'),
('Phone a Friend', 'Reach out to a friend or family member for a genuine conversation. Focus on connection rather than venting.', 'social', 30, 'easy', 'Reduces isolation, strengthens bonds, provides perspective, and releases oxytocin through social connection.', '/images/selfcare/phone.jpg'),
('Bedtime Routine Creation', 'Design a consistent 30-minute bedtime routine. Include winding down activities like reading, stretching, and screen-free time.', 'sleep', 30, 'moderate', 'Improves sleep quality, signals the body to rest, reduces insomnia, and creates a healthy habit.', '/images/selfcare/bedtime.jpg'),
('Positive Affirmation Mirror Work', 'Stand before a mirror and speak positive affirmations to yourself with eye contact. Start with three statements you genuinely believe.', 'emotional', 10, 'moderate', 'Builds self-esteem, challenges negative self-talk, reinforces positive beliefs, and practices self-compassion.', '/images/selfcare/mirror.jpg');

-- Coping Strategies
INSERT INTO coping_strategies (title, description, category, situation, effectiveness_rating, steps) VALUES
('Grounding 5-4-3-2-1 Technique', 'A sensory grounding exercise that uses all five senses to bring you back to the present moment during anxiety or panic.', 'anxiety', 'Panic attacks, anxiety spikes, dissociation', 5, '["Name 5 things you can see around you", "Name 4 things you can physically feel", "Name 3 things you can hear", "Name 2 things you can smell", "Name 1 thing you can taste", "Take three deep breaths and notice how you feel"]'),
('Thought Record', 'A CBT technique to identify, challenge, and reframe negative automatic thoughts that contribute to emotional distress.', 'cognitive', 'Negative thinking patterns, rumination, catastrophizing', 5, '["Write down the situation that triggered the emotion", "Identify the automatic negative thought", "Rate the intensity of the emotion (0-100)", "List evidence that supports the thought", "List evidence against the thought", "Create a balanced alternative thought", "Re-rate the emotion intensity"]'),
('STOP Technique', 'A mindfulness-based technique to pause reactive behavior: Stop, Take a breath, Observe, Proceed mindfully.', 'mindfulness', 'Reactive anger, impulsive decisions, emotional flooding', 4, '["STOP what you are doing", "TAKE a deep breath", "OBSERVE your thoughts, feelings, and sensations without judgment", "PROCEED mindfully, choosing a response rather than a reaction"]'),
('Worry Time Scheduling', 'Designate a specific 15-minute window each day for worrying. Outside this time, postpone worries to the scheduled slot.', 'anxiety', 'Chronic worry, generalized anxiety, overthinking', 4, '["Choose a consistent 15-minute daily worry time", "When worries arise outside this time, write them down", "Tell yourself you will address them during worry time", "During worry time, review your worry list", "For each worry, decide if action is needed or if you can let it go", "When the 15 minutes are up, stop and move on"]'),
('Opposite Action', 'A DBT skill where you act opposite to the urge created by an unhelpful emotion to change the emotional response.', 'emotional regulation', 'Depression urges to isolate, anxiety avoidance, anger aggression', 5, '["Identify the emotion you are experiencing", "Identify the action urge (e.g., isolate, avoid, lash out)", "Determine the opposite action (e.g., reach out, approach, be gentle)", "Throw yourself into the opposite action fully", "Repeat until the emotional intensity decreases"]'),
('Safe Place Visualization', 'Create a detailed mental image of a place where you feel completely safe, calm, and at peace.', 'anxiety', 'Anxiety, PTSD triggers, feeling unsafe, before sleep', 4, '["Close your eyes and take several deep breaths", "Imagine a place where you feel completely safe", "Add sensory details: sights, sounds, smells, textures", "Notice how your body feels in this safe place", "Choose a word or gesture to anchor this feeling", "Practice regularly so you can access it quickly when needed"]'),
('Behavioral Activation', 'Schedule and engage in meaningful activities to counteract depression withdrawal patterns.', 'depression', 'Depression, low motivation, withdrawal, anhedonia', 5, '["List activities that once brought you pleasure or sense of achievement", "Rate each from 1-10 for difficulty right now", "Start with the lowest difficulty activities", "Schedule one small activity per day", "Complete the activity regardless of motivation", "Rate your mood before and after", "Gradually increase activity complexity"]'),
('Distress Tolerance Ice Technique', 'Hold ice cubes or splash cold water on your face to activate the dive reflex and quickly reduce emotional intensity.', 'crisis', 'Intense emotional distress, self-harm urges, overwhelming feelings', 4, '["Get ice cubes or very cold water", "Hold ice cubes in your hands or place on your wrists", "Alternatively, splash cold water on your face", "Focus on the intense cold sensation", "Breathe through the sensation", "Notice how your emotional intensity decreases", "Repeat if needed"]'),
('Cognitive Defusion', 'An ACT technique to create distance from difficult thoughts by observing them without getting caught up in them.', 'cognitive', 'Intrusive thoughts, self-critical thoughts, worry spirals', 4, '["Notice the difficult thought", "Add the prefix: I am having the thought that...", "Then try: I notice I am having the thought that...", "Imagine placing the thought on a leaf floating down a stream", "Watch it float away without grabbing it", "Return your attention to the present moment"]'),
('RAIN Meditation', 'Recognize, Allow, Investigate, Nurture - a mindfulness approach to working with difficult emotions.', 'mindfulness', 'Strong emotions, emotional reactivity, self-judgment', 5, '["RECOGNIZE what is happening (name the emotion)", "ALLOW the experience to be there without pushing it away", "INVESTIGATE with kindness - where do you feel it in your body?", "NURTURE yourself with self-compassion", "Sit with whatever arises for a few minutes", "Notice any shifts in the emotional landscape"]'),
('Social Support Mapping', 'Identify and organize your support network so you know who to reach out to for different needs.', 'social', 'Isolation, feeling alone, not knowing who to call', 3, '["Draw three concentric circles", "Inner circle: closest supports (1-3 people)", "Middle circle: good friends and family (3-7 people)", "Outer circle: acquaintances and professional supports", "Note what each person is good at supporting (practical, emotional, fun)", "Keep this map accessible for difficult moments"]'),
('Radical Acceptance Practice', 'A DBT skill to fully accept reality as it is, without judgment, even when it is painful.', 'emotional regulation', 'Unchangeable situations, grief, chronic conditions, unfairness', 5, '["Acknowledge the reality of the situation", "Notice any resistance in your body or mind", "Remind yourself: fighting reality adds suffering", "Say to yourself: This is how it is right now", "Practice accepting with your whole body (relax tense muscles)", "Identify what you CAN control within this reality", "Choose how to move forward with acceptance"]'),
('Activity Scheduling for Anxiety', 'Pre-plan your day in blocks to reduce decision fatigue and the anxiety of uncertainty.', 'anxiety', 'Anticipatory anxiety, decision paralysis, unstructured time', 3, '["The evening before, write out tomorrow in time blocks", "Include both productive and restful activities", "Build in buffer time between activities", "Include one enjoyable activity", "When anxious about what to do next, consult your schedule", "Adjust the plan as needed without judgment"]'),
('Emotional Freedom Technique (Tapping)', 'Tap on specific acupressure points while focusing on a distressing emotion or thought to reduce its intensity.', 'somatic', 'Anxiety, phobias, emotional distress, negative beliefs', 4, '["Identify the issue and rate distress 0-10", "Create a setup statement: Even though I feel [emotion], I deeply accept myself", "Tap the side of your hand while repeating the setup 3 times", "Tap 5-7 times on each point: eyebrow, side of eye, under eye, under nose, chin, collarbone, under arm, top of head", "Focus on the feeling while tapping each point", "Take a deep breath and re-rate your distress"]'),
('Values Clarification Exercise', 'Identify your core values to guide decision-making and create a sense of purpose and direction.', 'existential', 'Feeling lost, lack of purpose, difficult decisions, life transitions', 4, '["Review a list of common values (family, creativity, health, etc.)", "Select your top 10 values", "Narrow down to your top 5", "For each value, write why it matters to you", "Rate how aligned your current life is with each value (1-10)", "Identify one small action for each value you can take this week", "Review and adjust monthly"]');

-- Assessments (PHQ-9, GAD-7, WHO-5)
INSERT INTO assessments (title, description, category, questions, scoring_guide) VALUES
('PHQ-9 Depression Screening', 'The Patient Health Questionnaire-9 is a validated tool for screening, diagnosing, monitoring, and measuring the severity of depression.', 'depression',
'[
  {"id": 1, "text": "Little interest or pleasure in doing things", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 2, "text": "Feeling down, depressed, or hopeless", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 3, "text": "Trouble falling or staying asleep, or sleeping too much", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 4, "text": "Feeling tired or having little energy", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 5, "text": "Poor appetite or overeating", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 6, "text": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 7, "text": "Trouble concentrating on things, such as reading the newspaper or watching television", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 8, "text": "Moving or speaking so slowly that other people could have noticed. Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 9, "text": "Thoughts that you would be better off dead, or of hurting yourself", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]}
]',
'{"ranges": [{"min": 0, "max": 4, "label": "Minimal depression", "description": "Your symptoms suggest minimal depression. Continue monitoring your mental health."}, {"min": 5, "max": 9, "label": "Mild depression", "description": "Your symptoms suggest mild depression. Consider lifestyle changes and watchful waiting."}, {"min": 10, "max": 14, "label": "Moderate depression", "description": "Your symptoms suggest moderate depression. Consider seeking professional support."}, {"min": 15, "max": 19, "label": "Moderately severe depression", "description": "Your symptoms suggest moderately severe depression. Professional treatment is recommended."}, {"min": 20, "max": 27, "label": "Severe depression", "description": "Your symptoms suggest severe depression. Please seek professional help promptly."}], "max_score": 27, "scoring": "Each question is scored 0-3 (Not at all=0, Several days=1, More than half the days=2, Nearly every day=3)"}'
),
('GAD-7 Anxiety Assessment', 'The Generalized Anxiety Disorder-7 is a validated screening tool for generalized anxiety disorder and assessing its severity.', 'anxiety',
'[
  {"id": 1, "text": "Feeling nervous, anxious, or on edge", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 2, "text": "Not being able to stop or control worrying", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 3, "text": "Worrying too much about different things", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 4, "text": "Trouble relaxing", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 5, "text": "Being so restless that it is hard to sit still", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 6, "text": "Becoming easily annoyed or irritable", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]},
  {"id": 7, "text": "Feeling afraid, as if something awful might happen", "options": ["Not at all", "Several days", "More than half the days", "Nearly every day"]}
]',
'{"ranges": [{"min": 0, "max": 4, "label": "Minimal anxiety", "description": "Your symptoms suggest minimal anxiety. No treatment is typically needed."}, {"min": 5, "max": 9, "label": "Mild anxiety", "description": "Your symptoms suggest mild anxiety. Monitor and consider self-help strategies."}, {"min": 10, "max": 14, "label": "Moderate anxiety", "description": "Your symptoms suggest moderate anxiety. Professional consultation is recommended."}, {"min": 15, "max": 21, "label": "Severe anxiety", "description": "Your symptoms suggest severe anxiety. Professional treatment is strongly recommended."}], "max_score": 21, "scoring": "Each question is scored 0-3 (Not at all=0, Several days=1, More than half the days=2, Nearly every day=3)"}'
),
('WHO-5 Well-Being Index', 'The World Health Organization Well-Being Index is a short questionnaire measuring current mental well-being over the past two weeks.', 'wellbeing',
'[
  {"id": 1, "text": "I have felt cheerful and in good spirits", "options": ["At no time", "Some of the time", "Less than half the time", "More than half the time", "Most of the time", "All of the time"]},
  {"id": 2, "text": "I have felt calm and relaxed", "options": ["At no time", "Some of the time", "Less than half the time", "More than half the time", "Most of the time", "All of the time"]},
  {"id": 3, "text": "I have felt active and vigorous", "options": ["At no time", "Some of the time", "Less than half the time", "More than half the time", "Most of the time", "All of the time"]},
  {"id": 4, "text": "I woke up feeling fresh and rested", "options": ["At no time", "Some of the time", "Less than half the time", "More than half the time", "Most of the time", "All of the time"]},
  {"id": 5, "text": "My daily life has been filled with things that interest me", "options": ["At no time", "Some of the time", "Less than half the time", "More than half the time", "Most of the time", "All of the time"]}
]',
'{"ranges": [{"min": 0, "max": 28, "label": "Low well-being", "description": "Your score suggests low well-being. Screening for depression is recommended."}, {"min": 29, "max": 50, "label": "Moderate well-being", "description": "Your well-being is moderate. Consider strategies to improve your daily satisfaction."}, {"min": 51, "max": 100, "label": "High well-being", "description": "Your well-being is high. Continue your current practices to maintain good mental health."}], "max_score": 100, "scoring": "Each question is scored 0-5. Raw score is multiplied by 4 to get percentage score (0-100)."}'
);

-- Goals (for user_id=1)
INSERT INTO goals (user_id, title, description, category, target_date, progress, status, milestones) VALUES
(1, 'Meditate Daily for 30 Days', 'Build a consistent daily meditation practice starting with 5 minutes and working up to 20 minutes.', 'mindfulness', '2026-04-15', 40, 'active', '[{"title": "Complete first week (5 min/day)", "completed": true}, {"title": "Increase to 10 minutes", "completed": true}, {"title": "Complete two weeks", "completed": false}, {"title": "Increase to 15 minutes", "completed": false}, {"title": "Complete 30 days", "completed": false}]'),
(1, 'Improve Sleep Hygiene', 'Establish a consistent sleep schedule with 7-8 hours per night and a calming bedtime routine.', 'sleep', '2026-05-01', 25, 'active', '[{"title": "Set consistent bedtime", "completed": true}, {"title": "Remove screens from bedroom", "completed": false}, {"title": "Create bedtime routine", "completed": false}, {"title": "Achieve 7+ hours for one week", "completed": false}]'),
(1, 'Journal Three Times per Week', 'Develop a regular journaling habit to process emotions and track personal growth.', 'emotional', '2026-04-30', 60, 'active', '[{"title": "Buy a dedicated journal", "completed": true}, {"title": "Write first entry", "completed": true}, {"title": "Complete one week", "completed": true}, {"title": "Complete one month", "completed": false}]'),
(1, 'Run a 5K', 'Train for and complete a 5K run as part of physical and mental health improvement.', 'physical', '2026-06-01', 30, 'active', '[{"title": "Start walking 30 min/day", "completed": true}, {"title": "Begin Couch to 5K program", "completed": true}, {"title": "Run 1 mile without stopping", "completed": false}, {"title": "Run 3 miles", "completed": false}, {"title": "Complete 5K event", "completed": false}]'),
(1, 'Reduce Screen Time', 'Limit recreational screen time to 2 hours per day and eliminate screens before bed.', 'lifestyle', '2026-04-15', 20, 'active', '[{"title": "Install screen time tracker", "completed": true}, {"title": "Set daily limits", "completed": false}, {"title": "Find alternative activities", "completed": false}, {"title": "Achieve goal for one week", "completed": false}]'),
(1, 'Practice Gratitude Daily', 'Write three things I am grateful for every evening before bed.', 'emotional', '2026-05-15', 50, 'active', '[{"title": "Get gratitude journal", "completed": true}, {"title": "Write daily for one week", "completed": true}, {"title": "Write daily for one month", "completed": false}, {"title": "Share gratitude with others weekly", "completed": false}]'),
(1, 'Learn to Cook Healthy Meals', 'Master 10 healthy recipes that support mental health through proper nutrition.', 'nutrition', '2026-06-30', 30, 'active', '[{"title": "Research brain-healthy foods", "completed": true}, {"title": "Plan weekly menu", "completed": true}, {"title": "Cook 3 new recipes", "completed": false}, {"title": "Cook 7 new recipes", "completed": false}, {"title": "Master 10 recipes", "completed": false}]'),
(1, 'Attend Weekly Therapy', 'Maintain consistent weekly therapy sessions and complete homework assignments.', 'therapy', '2026-07-01', 45, 'active', '[{"title": "Find a therapist", "completed": true}, {"title": "Attend first session", "completed": true}, {"title": "Complete 4 sessions", "completed": true}, {"title": "Complete 12 sessions", "completed": false}]'),
(1, 'Build a Support Network', 'Identify and strengthen relationships with at least 5 supportive people.', 'social', '2026-06-01', 35, 'active', '[{"title": "Identify current supports", "completed": true}, {"title": "Reconnect with one old friend", "completed": true}, {"title": "Join a support group", "completed": false}, {"title": "Schedule regular social activities", "completed": false}]'),
(1, 'Practice Self-Compassion', 'Develop a kinder inner dialogue and reduce self-criticism.', 'emotional', '2026-05-30', 25, 'active', '[{"title": "Read self-compassion book", "completed": true}, {"title": "Practice self-compassion meditation weekly", "completed": false}, {"title": "Challenge self-critical thoughts daily", "completed": false}, {"title": "Write self-compassion letter", "completed": false}]'),
(1, 'Reduce Caffeine Intake', 'Gradually reduce caffeine from 4 cups to 1 cup of coffee per day.', 'physical', '2026-04-30', 50, 'active', '[{"title": "Track current intake", "completed": true}, {"title": "Reduce to 3 cups", "completed": true}, {"title": "Reduce to 2 cups", "completed": false}, {"title": "Reduce to 1 cup", "completed": false}]'),
(1, 'Complete CBT Workbook', 'Work through a cognitive behavioral therapy workbook to build coping skills.', 'therapy', '2026-06-15', 20, 'active', '[{"title": "Purchase workbook", "completed": true}, {"title": "Complete chapters 1-3", "completed": false}, {"title": "Complete chapters 4-6", "completed": false}, {"title": "Complete all chapters", "completed": false}]'),
(1, 'Volunteer Monthly', 'Contribute to the community by volunteering at least once a month for a cause I care about.', 'purpose', '2026-12-31', 15, 'active', '[{"title": "Research volunteer opportunities", "completed": true}, {"title": "Complete first volunteer session", "completed": false}, {"title": "Volunteer 3 months in a row", "completed": false}, {"title": "Volunteer 6 months in a row", "completed": false}]'),
(1, 'Digital Mindfulness Practice', 'Develop a healthier relationship with technology through intentional use and regular breaks.', 'mindfulness', '2026-05-01', 10, 'active', '[{"title": "Audit current digital habits", "completed": true}, {"title": "Implement phone-free meals", "completed": false}, {"title": "Take weekly digital sabbath", "completed": false}, {"title": "Maintain for one month", "completed": false}]'),
(1, 'Improve Work-Life Balance', 'Set clear boundaries between work and personal time to prevent burnout.', 'lifestyle', '2026-05-15', 20, 'active', '[{"title": "Define work hours", "completed": true}, {"title": "Create end-of-day ritual", "completed": false}, {"title": "Stop checking email after hours", "completed": false}, {"title": "Take all vacation days", "completed": false}]');

-- Support Groups
INSERT INTO support_groups (name, description, category, meeting_schedule, max_members, current_members, facilitator, is_active) VALUES
('Anxiety Warriors', 'A supportive group for individuals managing anxiety disorders. Share coping strategies and find community.', 'anxiety', 'Tuesdays and Thursdays, 7:00 PM EST', 20, 14, 'Dr. Sarah Mitchell', true),
('Depression Recovery Circle', 'A compassionate space for those navigating depression. Focus on behavioral activation and peer support.', 'depression', 'Mondays and Wednesdays, 6:30 PM EST', 15, 11, 'Dr. James Rivera', true),
('Mindfulness Practice Group', 'Weekly group meditation and mindfulness discussion. All experience levels welcome.', 'mindfulness', 'Saturdays, 9:00 AM EST', 25, 18, 'Lisa Chen, LMFT', true),
('Grief and Loss Support', 'A gentle space for processing grief and loss. Honor your loved ones while finding your path forward.', 'grief', 'Wednesdays, 7:00 PM EST', 12, 8, 'Maria Rodriguez, LCSW', true),
('PTSD Recovery Group', 'For survivors of trauma working toward recovery. Uses evidence-based trauma-informed approaches.', 'trauma', 'Tuesdays, 6:00 PM EST', 10, 7, 'Dr. Michael Thompson', true),
('Young Adults Mental Health', 'A group for adults ages 18-30 navigating mental health challenges during life transitions.', 'general', 'Thursdays, 8:00 PM EST', 20, 16, 'Alex Park, LPC', true),
('Stress Management Workshop', 'Learn and practice evidence-based stress management techniques in a supportive group setting.', 'stress', 'Mondays, 12:00 PM EST', 25, 19, 'Dr. Emily Watson', true),
('Bipolar Support Network', 'For individuals living with bipolar disorder. Share experiences and strategies for mood stability.', 'bipolar', 'Wednesdays, 7:30 PM EST', 15, 10, 'Dr. Robert Kim', true),
('OCD Support Circle', 'A supportive environment for those managing OCD. Learn about ERP and share recovery stories.', 'ocd', 'Fridays, 6:00 PM EST', 12, 9, 'Jennifer Walsh, PhD', true),
('Caregiver Wellness Group', 'Supporting those who care for others with mental health conditions. Focus on preventing caregiver burnout.', 'caregiver', 'Saturdays, 10:30 AM EST', 15, 11, 'Nancy Adams, LCSW', true),
('Social Anxiety Group', 'Practice social skills and build confidence in a safe, non-judgmental environment.', 'social anxiety', 'Thursdays, 6:30 PM EST', 10, 8, 'Dr. David Lee', true),
('Addiction Recovery Support', 'Dual diagnosis support for those managing both addiction and mental health challenges.', 'addiction', 'Daily, 5:30 PM EST', 20, 15, 'Mark Stevens, CADC', true),
('Women Mental Health Circle', 'A women-only space addressing unique mental health challenges including postpartum, hormonal, and societal pressures.', 'women', 'Tuesdays, 7:30 PM EST', 15, 12, 'Dr. Amanda Foster', true),
('Veterans Mental Health Support', 'A group specifically for military veterans dealing with PTSD, transition stress, and other mental health concerns.', 'veterans', 'Saturdays, 2:00 PM EST', 15, 9, 'Captain (Ret.) Tom Bradley, LMFT', true),
('Insomnia and Sleep Issues Group', 'For those struggling with sleep disorders. Learn CBT-I techniques and share what works.', 'sleep', 'Mondays, 8:00 PM EST', 15, 13, 'Dr. Rachel Green', true);

-- Crisis Resources
INSERT INTO crisis_resources (name, description, phone, text_line, website, hours, category, is_emergency) VALUES
('988 Suicide & Crisis Lifeline', 'Free, confidential crisis support for anyone in suicidal crisis or emotional distress.', '988', 'Text 988', 'https://988lifeline.org', '24/7', 'suicide prevention', true),
('Crisis Text Line', 'Free, 24/7 crisis support via text message. Trained crisis counselors provide support.', NULL, 'Text HOME to 741741', 'https://www.crisistextline.org', '24/7', 'general crisis', true),
('National Domestic Violence Hotline', 'Support for anyone affected by domestic violence. Confidential and available in 200+ languages.', '1-800-799-7233', 'Text START to 88788', 'https://www.thehotline.org', '24/7', 'domestic violence', true),
('SAMHSA National Helpline', 'Free referral service for substance abuse and mental health treatment facilities and support groups.', '1-800-662-4357', NULL, 'https://www.samhsa.gov/find-help/national-helpline', '24/7', 'substance abuse', false),
('Veterans Crisis Line', 'Crisis support specifically for veterans, service members, and their families.', '988 (Press 1)', 'Text 838255', 'https://www.veteranscrisisline.net', '24/7', 'veterans', true),
('Trevor Project', 'Crisis intervention and suicide prevention for LGBTQ+ young people ages 13-24.', '1-866-488-7386', 'Text START to 678-678', 'https://www.thetrevorproject.org', '24/7', 'LGBTQ+ youth', true),
('NAMI Helpline', 'Information, referrals, and support for people living with mental health conditions and their families.', '1-800-950-6264', 'Text NAMI to 741741', 'https://www.nami.org/help', 'Mon-Fri 10AM-10PM EST', 'general mental health', false),
('Childhelp National Child Abuse Hotline', 'Crisis intervention, information, and referrals for child abuse situations.', '1-800-422-4453', NULL, 'https://www.childhelp.org/hotline', '24/7', 'child abuse', true),
('National Eating Disorders Association', 'Support, resources, and treatment options for those struggling with eating disorders.', '1-800-931-2237', 'Text NEDA to 741741', 'https://www.nationaleatingdisorders.org', 'Mon-Thu 11AM-9PM EST, Fri 11AM-5PM EST', 'eating disorders', false),
('Disaster Distress Helpline', 'Crisis counseling for people experiencing emotional distress related to natural or human-caused disasters.', '1-800-985-5990', 'Text TalkWithUs to 66746', 'https://www.samhsa.gov/find-help/disaster-distress-helpline', '24/7', 'disaster', false),
('National Sexual Assault Hotline', 'Confidential support from trained staff for survivors of sexual assault.', '1-800-656-4673', NULL, 'https://www.rainn.org', '24/7', 'sexual assault', true),
('Trans Lifeline', 'Peer support hotline run by and for transgender people in crisis.', '1-877-565-8860', NULL, 'https://translifeline.org', '24/7', 'transgender', true),
('Postpartum Support International', 'Support for families dealing with perinatal mood and anxiety disorders.', '1-800-944-4773', 'Text 503-894-9453', 'https://www.postpartum.net', 'Mon-Fri 9AM-5PM EST', 'postpartum', false),
('National Alliance on Mental Illness (NAMI) Crisis Line', 'Immediate crisis support and mental health resource navigation.', '1-800-950-6264', NULL, 'https://www.nami.org', 'Mon-Fri 10AM-10PM EST', 'general crisis', false),
('Alcoholics Anonymous', 'Support for individuals struggling with alcohol addiction through peer fellowship.', '1-212-870-3400', NULL, 'https://www.aa.org', '24/7 (varies by location)', 'addiction', false);

-- Affirmations
INSERT INTO affirmations (text, category, author) VALUES
('I am worthy of love and belonging, exactly as I am right now.', 'self-worth', 'Brene Brown'),
('My anxiety does not define me. I am so much more than my worries.', 'anxiety', NULL),
('I give myself permission to rest without guilt. Rest is productive.', 'self-care', NULL),
('Every small step forward is still progress. I celebrate my efforts.', 'motivation', NULL),
('I am allowed to set boundaries that protect my peace and energy.', 'boundaries', NULL),
('My feelings are valid. I do not need to justify my emotions to anyone.', 'emotional validation', NULL),
('I choose to respond with compassion, starting with myself.', 'self-compassion', NULL),
('Today I release what I cannot control and focus on what I can.', 'acceptance', NULL),
('I am resilient. I have overcome challenges before and I will again.', 'resilience', NULL),
('My mental health journey is unique and I honor my own timeline.', 'mental health', NULL),
('I deserve the same kindness I so freely give to others.', 'self-compassion', NULL),
('Healing is not linear. Bad days do not erase my progress.', 'healing', NULL),
('I am brave for showing up today, even when it is hard.', 'courage', NULL),
('I trust myself to handle whatever comes my way, one moment at a time.', 'trust', NULL),
('My vulnerability is a strength, not a weakness. It connects me to others.', 'vulnerability', 'Brene Brown');

-- Sleep Logs (for user_id=1)
INSERT INTO sleep_logs (user_id, sleep_date, bedtime, wake_time, duration_hours, quality, notes, factors) VALUES
(1, '2026-03-01', '22:30', '06:30', 8.0, 8, 'Fell asleep quickly after meditation. Woke up feeling refreshed.', ARRAY['meditation', 'consistent schedule']),
(1, '2026-03-02', '23:15', '06:45', 7.5, 6, 'Took a while to fall asleep. Mind was racing about work.', ARRAY['work stress', 'late caffeine']),
(1, '2026-03-03', '00:00', '07:30', 7.5, 5, 'Stayed up too late watching TV. Woke up groggy.', ARRAY['screen time', 'late bedtime']),
(1, '2026-03-04', '22:00', '06:00', 8.0, 9, 'Perfect night of sleep. Exercise earlier in the day helped.', ARRAY['exercise', 'early bedtime', 'no screens']),
(1, '2026-03-05', '23:00', '05:30', 6.5, 4, 'Woke up at 3 AM and could not fall back asleep for an hour.', ARRAY['anxiety', 'middle-of-night waking']),
(1, '2026-03-06', '22:45', '06:30', 7.75, 7, 'Decent sleep. Used white noise machine.', ARRAY['white noise', 'consistent routine']),
(1, '2026-03-07', '21:30', '06:00', 8.5, 9, 'Went to bed early after a long hike. Slept deeply.', ARRAY['exercise', 'physical exhaustion', 'early bedtime']),
(1, '2026-03-08', '01:00', '08:00', 7.0, 3, 'Insomnia. Could not stop worrying. Finally fell asleep after breathing exercises.', ARRAY['insomnia', 'anxiety', 'late bedtime']),
(1, '2026-03-09', '22:30', '06:30', 8.0, 7, 'Good routine night. Chamomile tea before bed helped.', ARRAY['herbal tea', 'routine']),
(1, '2026-03-10', '23:30', '07:00', 7.5, 6, 'Neighbors were noisy until midnight. Eventually used earplugs.', ARRAY['noise', 'earplugs']),
(1, '2026-03-11', '22:00', '06:15', 8.25, 8, 'Used 4-7-8 breathing before sleep. Very relaxing.', ARRAY['breathing exercises', 'relaxation']),
(1, '2026-03-12', '22:15', '06:00', 7.75, 7, 'Steady sleep but had some vivid dreams.', ARRAY['dreams', 'moderate quality']),
(1, '2026-03-13', '23:45', '06:30', 6.75, 4, 'Late dinner made it hard to sleep. Felt uncomfortable.', ARRAY['late eating', 'discomfort']),
(1, '2026-03-14', '22:00', '06:30', 8.5, 9, 'Weekend sleep. No alarm. Body woke naturally. Felt amazing.', ARRAY['natural waking', 'no alarm', 'weekend']),
(1, '2026-03-15', '22:30', '06:15', 7.75, 7, 'Good sleep after journaling before bed. Mind felt clear.', ARRAY['journaling', 'mental clarity']);

-- Gratitude Entries (for user_id=1)
INSERT INTO gratitude_entries (user_id, title, entry_text, category, intensity) VALUES
(1, 'Morning Coffee Ritual', 'Grateful for my morning coffee ritual. Those quiet 15 minutes before the world wakes up are sacred. The warmth of the mug, the aroma filling the kitchen - it grounds me for the day ahead.', 'personal', 8),
(1, 'Safe Space in Therapy', 'Thankful for my therapist who creates such a safe space for me to be vulnerable and grow. Today we worked through a childhood memory that I have been carrying for years.', 'health', 9),
(1, 'Sunset on My Walk', 'Grateful for the sunset I witnessed on my evening walk. Nature reminds me there is beauty in endings. The sky was painted in shades of orange and purple.', 'nature', 7),
(1, 'My Resilient Body', 'Thankful for my body that carries me through each day, even when I forget to appreciate it. Despite the aches, it shows up for me every single morning.', 'health', 8),
(1, 'A Friend Who Cares', 'Grateful for my best friend who checked in on me today without me having to ask. She just knew. That kind of connection is rare and precious.', 'relationships', 9),
(1, 'The Gift of Reading', 'Thankful for the ability to read. Books have been my companions through the darkest times. Finished a chapter that felt like it was written just for me.', 'personal', 7),
(1, 'A Warm Safe Home', 'Grateful for a warm bed and a safe home. Not everyone has this privilege. Tonight the rain is falling and I feel so cozy and protected.', 'personal', 8),
(1, 'Learning to Say No', 'Thankful for the courage I found to say no today. Boundaries are an act of self-respect. It felt uncomfortable but also empowering.', 'personal', 9),
(1, 'Music Heals', 'Grateful for music. The right song at the right time can change everything. Heard an old favorite today and felt a wave of peace wash over me.', 'personal', 7),
(1, 'Clean Water and Nourishment', 'Thankful for clean water, nutritious food, and access to healthcare. These are not guaranteed for everyone. I will not take them for granted.', 'health', 6),
(1, 'Lessons from Mistakes', 'Grateful for the mistakes I have made. They were painful but they taught me who I really am. Each stumble redirected me to a better path.', 'personal', 8),
(1, 'Spring Renewal', 'Thankful for the changing seasons. Spring reminds me that renewal is always possible. The first blossoms appeared on the tree outside my window today.', 'nature', 7),
(1, 'Investing in Myself', 'Grateful for this mental health journey and the work I am doing on myself. Showing up matters, even on the hard days.', 'health', 9),
(1, 'Pure Laughter', 'Thankful for laughter. My coworker told the funniest story today and I laughed until I cried. Joy is medicine.', 'relationships', 8),
(1, 'Peaceful Stillness', 'Grateful for the quiet moments between activities. Stillness is where I find myself. Five minutes of silence today felt like a gift.', 'personal', 6);

-- Therapists
INSERT INTO therapists (name, title, specializations, approach, experience_years, rating, reviews_count, phone, email, website, address, accepts_insurance, price_range, availability, image_url, bio) VALUES
('Dr. Sarah Mitchell', 'Licensed Clinical Psychologist', ARRAY['anxiety', 'depression', 'PTSD', 'trauma'], 'Cognitive Behavioral Therapy (CBT)', 15, 4.92, 127, '(555) 234-5678', 'dr.mitchell@therapyworks.com', 'https://www.drmitchelltherapy.com', '123 Wellness Blvd, Suite 200, New York, NY 10001', true, '$150-$250/session', 'Mon-Thu 9AM-6PM', '/images/therapists/mitchell.jpg', 'Dr. Mitchell specializes in evidence-based treatment for anxiety and trauma disorders. With 15 years of experience, she combines CBT with mindfulness-based approaches to help clients develop lasting coping skills and resilience.'),
('Dr. James Rivera', 'Licensed Psychiatrist, MD', ARRAY['depression', 'bipolar disorder', 'medication management', 'mood disorders'], 'Integrative Psychiatry', 20, 4.88, 203, '(555) 345-6789', 'dr.rivera@mindhealth.com', 'https://www.riverapsychiatry.com', '456 Mental Health Ave, Suite 100, New York, NY 10002', true, '$200-$350/session', 'Mon-Fri 8AM-5PM', '/images/therapists/rivera.jpg', 'Dr. Rivera is a board-certified psychiatrist with expertise in mood disorders and medication management. He takes a holistic approach, combining pharmacotherapy with psychotherapy for comprehensive mental health care.'),
('Lisa Chen', 'Licensed Marriage and Family Therapist', ARRAY['couples therapy', 'family conflict', 'relationship issues', 'communication'], 'Emotionally Focused Therapy (EFT)', 12, 4.95, 89, '(555) 456-7890', 'lisa@chenfamilytherapy.com', 'https://www.lisachentherapy.com', '789 Harmony Lane, Suite 305, San Francisco, CA 94102', true, '$130-$200/session', 'Tue-Sat 10AM-7PM', '/images/therapists/chen.jpg', 'Lisa is passionate about helping couples and families rebuild connection and trust. Using Emotionally Focused Therapy, she guides clients toward understanding their attachment patterns and creating secure, loving relationships.'),
('Dr. Michael Thompson', 'Licensed Clinical Psychologist', ARRAY['PTSD', 'veterans', 'trauma recovery', 'EMDR'], 'EMDR and Trauma-Focused CBT', 18, 4.90, 156, '(555) 567-8901', 'dr.thompson@veteransmentalhealth.com', 'https://www.thompsonpsych.com', '321 Oak Street, Suite 400, Chicago, IL 60601', true, '$175-$275/session', 'Mon-Fri 9AM-5PM', '/images/therapists/thompson.jpg', 'Dr. Thompson is a veteran himself and specializes in helping service members and veterans process trauma using EMDR and evidence-based trauma therapies. He understands the unique challenges of military life firsthand.'),
('Maria Rodriguez', 'Licensed Clinical Social Worker', ARRAY['grief', 'loss', 'life transitions', 'cultural identity'], 'Narrative Therapy', 10, 4.87, 74, '(555) 678-9012', 'maria@rodrigueztherapy.com', 'https://www.mariarodriguezlcsw.com', '654 Elm Drive, Suite 150, Miami, FL 33101', true, '$100-$175/session', 'Mon-Thu 10AM-8PM', '/images/therapists/rodriguez.jpg', 'Maria specializes in grief counseling and helping individuals navigate major life transitions. Bilingual in English and Spanish, she is committed to providing culturally sensitive care that honors each clients unique background and story.'),
('Alex Park', 'Licensed Professional Counselor', ARRAY['young adults', 'identity', 'career counseling', 'life purpose'], 'Acceptance and Commitment Therapy (ACT)', 8, 4.93, 62, '(555) 789-0123', 'alex@parktherapy.com', 'https://www.alexparklpc.com', '987 Pine Avenue, Suite 250, Portland, OR 97201', true, '$120-$180/session', 'Mon-Fri 11AM-8PM', '/images/therapists/park.jpg', 'Alex works primarily with young adults navigating the challenges of early adulthood, including career decisions, identity exploration, and building meaningful lives. Using ACT, they help clients clarify values and take committed action.'),
('Dr. Emily Watson', 'Licensed Clinical Psychologist', ARRAY['OCD', 'anxiety disorders', 'phobias', 'perfectionism'], 'Exposure and Response Prevention (ERP)', 14, 4.91, 118, '(555) 890-1234', 'dr.watson@ocdspecialist.com', 'https://www.drwatsonpsych.com', '147 Cedar Court, Suite 500, Boston, MA 02101', true, '$160-$240/session', 'Tue-Fri 9AM-6PM', '/images/therapists/watson.jpg', 'Dr. Watson is one of the regions leading OCD specialists. She uses Exposure and Response Prevention, the gold standard treatment for OCD, helping clients gradually face their fears and break free from compulsive patterns.'),
('Dr. Robert Kim', 'Licensed Psychiatrist, MD', ARRAY['bipolar disorder', 'schizophrenia', 'psychotic disorders', 'medication management'], 'Psychopharmacology', 22, 4.85, 178, '(555) 901-2345', 'dr.kim@psychiatriccare.com', 'https://www.drkimpsychiatry.com', '258 Birch Boulevard, Suite 300, Los Angeles, CA 90001', true, '$225-$375/session', 'Mon-Thu 8AM-4PM', '/images/therapists/kim.jpg', 'Dr. Kim is a board-certified psychiatrist with over two decades of experience in treating severe mental illness. He is known for his thorough diagnostic approach and his ability to find the right medication balance for each patient.'),
('Jennifer Walsh', 'Licensed Clinical Psychologist, PhD', ARRAY['eating disorders', 'body image', 'self-esteem', 'womens health'], 'Dialectical Behavior Therapy (DBT)', 16, 4.94, 95, '(555) 012-3456', 'jennifer@walshpsychology.com', 'https://www.jenniferwalshphd.com', '369 Maple Street, Suite 175, Denver, CO 80201', true, '$145-$225/session', 'Mon-Fri 9AM-6PM', '/images/therapists/walsh.jpg', 'Dr. Walsh combines DBT with a compassionate, body-positive approach to help clients heal from eating disorders and develop a healthier relationship with themselves. She is a nationally recognized expert in the field.'),
('Nancy Adams', 'Licensed Clinical Social Worker', ARRAY['caregiver burnout', 'elder care', 'family dynamics', 'stress management'], 'Solution-Focused Brief Therapy', 11, 4.86, 83, '(555) 123-4567', 'nancy@adamscounseling.com', 'https://www.nancyadamslcsw.com', '741 Willow Way, Suite 225, Seattle, WA 98101', true, '$110-$170/session', 'Mon-Wed 9AM-5PM, Thu 9AM-8PM', '/images/therapists/adams.jpg', 'Nancy specializes in supporting caregivers and families navigating the challenges of caring for loved ones with mental health conditions or chronic illness. She provides practical, solution-focused strategies for managing stress and preventing burnout.'),
('Dr. David Lee', 'Licensed Clinical Psychologist', ARRAY['social anxiety', 'autism spectrum', 'social skills', 'selective mutism'], 'Social Skills Training and CBT', 13, 4.89, 101, '(555) 234-5670', 'dr.lee@socialanxietyhelp.com', 'https://www.drleepsychology.com', '852 Spruce Lane, Suite 400, Austin, TX 78701', true, '$140-$220/session', 'Tue-Sat 10AM-7PM', '/images/therapists/lee.jpg', 'Dr. Lee specializes in social anxiety and autism spectrum conditions. He creates a warm, patient environment where clients can practice social skills at their own pace and build confidence in social situations.'),
('Dr. Amanda Foster', 'Licensed Clinical Psychologist', ARRAY['postpartum depression', 'perinatal mental health', 'womens issues', 'hormonal mood changes'], 'Interpersonal Therapy (IPT)', 12, 4.96, 88, '(555) 345-6780', 'dr.foster@maternalmentalhealth.com', 'https://www.dramandafoster.com', '963 Rose Avenue, Suite 150, Nashville, TN 37201', true, '$135-$210/session', 'Mon-Fri 9AM-5PM', '/images/therapists/foster.jpg', 'Dr. Foster is dedicated to supporting women through all stages of motherhood. From fertility challenges to postpartum mood disorders, she provides compassionate, evidence-based care that addresses the unique mental health needs of women.'),
('Mark Stevens', 'Certified Addiction Counselor', ARRAY['addiction', 'dual diagnosis', 'recovery', 'relapse prevention'], 'Motivational Interviewing', 17, 4.82, 134, '(555) 456-7891', 'mark@stevensrecovery.com', 'https://www.markstevensrecovery.com', '159 Recovery Road, Suite 100, Philadelphia, PA 19101', true, '$95-$160/session', 'Mon-Sat 8AM-6PM', '/images/therapists/stevens.jpg', 'Mark is a certified addiction counselor in long-term recovery himself. He brings both professional expertise and personal understanding to help clients navigate the complex journey of recovery from substance use disorders.'),
('Captain (Ret.) Tom Bradley', 'Licensed Marriage and Family Therapist', ARRAY['veterans', 'military families', 'transition stress', 'couples counseling'], 'Gottman Method and Trauma-Informed Care', 14, 4.91, 76, '(555) 567-8902', 'tom@bradleyveteranscounseling.com', 'https://www.bradleycounseling.com', '753 Liberty Street, Suite 200, San Diego, CA 92101', true, '$125-$195/session', 'Mon-Fri 9AM-6PM', '/images/therapists/bradley.jpg', 'Captain Bradley served 20 years in the military before becoming a therapist. He specializes in helping veterans and military families navigate the unique challenges of service life, including deployment stress, reintegration, and relationship issues.'),
('Dr. Rachel Green', 'Licensed Clinical Psychologist', ARRAY['insomnia', 'sleep disorders', 'CBT-I', 'circadian rhythm disorders'], 'Cognitive Behavioral Therapy for Insomnia (CBT-I)', 10, 4.93, 67, '(555) 678-9013', 'dr.green@sleepwellclinic.com', 'https://www.drrachelgreen.com', '357 Restful Drive, Suite 350, Minneapolis, MN 55401', true, '$150-$230/session', 'Mon-Thu 10AM-7PM', '/images/therapists/green.jpg', 'Dr. Green is a sleep psychologist specializing in CBT-I, the gold standard non-medication treatment for chronic insomnia. She helps clients develop healthy sleep habits and overcome the anxiety and behaviors that perpetuate sleep difficulties.');
